volumes:
  staticbuild:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - staticbuild:/app/.next

  web:
    image: nginx:alpine
    container_name: serverapp
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - staticbuild:/usr/share/nginx/html
    ports:
      - "8000:80"
    links:
      - "app"
    depends_on:
      - "app"
